export type ParsedDuty={driver_name:string|null;vehicle_id:string|null;vehicle_type:string|null;seats:number;start_time:string|null;pickup_time:string|null;leave_time:string|null;arrival_time:string|null;finish_time:string|null;origin:string|null;destination:string|null;stay:boolean;back:boolean;raw_text:string;sort_order:number};
const clean=(v:unknown)=>{const x=String(v??"").replace(/\s+/g," ").trim();return x||null};
const time=(v:unknown)=>{const x=clean(v);const m=x?.match(/(\d{2}:\d{2})/);return m?.[1]??null};
const nonDrivers=new Set(["ON HIRE","Bus St","Bus School","Shuttle Bus School","Grammar School","Hotel MUFC","Station timetable","RUN RUN","RUN","School","Comment","Holiday","Sick","Unscheduled",".Rest Day"]);
const row=/^(?:(?<driver>[A-Za-zÀ-ÿ'’.-]+(?:\s+[A-Za-zÀ-ÿ'’.-]+){1,4})\s+)?(?<start>(?:\d{2}:\d{2}|\?\?:\?\?))\s+(?<pickup>(?:\d{2}:\d{2}|\?\?:\?\?))\s+(?<origin>.*?)\s+(?<backFlag>Yes|No)\s+(?<stay>Yes|No)\s+(?<destination>.*?)\s+(?<times>(?:(?:\d{2}:\d{2}|\?\?:\?\?)\s*){3,4})(?<seats>\d{1,3})\s+(?<tail>.+)$/;
const driverLine=/^[A-Za-zÀ-ÿ'’.-]+(?:\s+[A-Za-zÀ-ÿ'’.-]+){1,4}$/;
export function parseCoachManagerText(text:string):ParsedDuty[]{const lines=text.replace(/\r/g,"").split(/\n+/).map(clean).filter(Boolean) as string[];const out:ParsedDuty[]=[];let currentDriver:string|null=null;
for(const line of lines){if(/^(Coach Manager Printed:|Bookings - Driver Order|Driver Name Start|Record Count =|ORDER BY DriverID|Driver Name Driver Type)/.test(line))continue;const m=row.exec(line);
if(!m?.groups){if(driverLine.test(line)&&!nonDrivers.has(line)&&!line.includes("Printed")){const d=line.trim();if(out.length&&!out[out.length-1].driver_name)out[out.length-1].driver_name=d;currentDriver=d;}continue}
const g=m.groups;const ts=(clean(g.times)??"").split(/\s+/);const tail=clean(g.tail)??"";
const prefixes=["38EXEC VIP","CAR SDSC","VIPCoach","PSVAR+1","DDSC","DDSB","SDSB","SDSC","Executive","CAR","EXEC"];const prefix=prefixes.find(p=>tail.startsWith(p+" ")||tail===p);const remainder=(prefix?tail.slice(prefix.length):tail).trim();const vehicleId=remainder.split(/\s+/)[0]?.toUpperCase()??null;const vehicleType=prefix??null;
const candidate=clean(g.driver);if(candidate&&!nonDrivers.has(candidate))currentDriver=candidate;
out.push({driver_name:currentDriver,vehicle_id:vehicleId,vehicle_type:vehicleType||null,seats:Number(g.seats),start_time:time(g.start),pickup_time:time(g.pickup),leave_time:time(ts[1]),arrival_time:time(ts[0]),finish_time:time(ts.length===4?ts[3]:ts[2]),origin:clean(g.origin),destination:clean(g.destination),stay:g.stay==="Yes",back:g.backFlag==="Yes",raw_text:line,sort_order:out.length+1});}
return out}
const csvValue=(row:Record<string,string>,names:string[])=>{const key=Object.keys(row).find(k=>names.includes(k.toLowerCase().replace(/[^a-z0-9]/g,"")));return key?clean(row[key]):null};
function parseCsvRows(text:string):Record<string,string>[] { const lines=text.replace(/^\uFEFF/,"").replace(/\r/g,"").split("\n").filter((x:string)=>x.trim()); if(lines.length<2)return []; const cells=(line:string)=>{const out:string[]=[];let cur="",quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quote&&line[i+1]==='"'){cur+='"';i++;}else quote=!quote;}else if(c===','&&!quote){out.push(cur.trim());cur="";}else cur+=c;}out.push(cur.trim());return out;}; const headers=cells(lines[0]).map(x=>x.toLowerCase().replace(/[^a-z0-9]/g,"")); return lines.slice(1).map(line=>{const vals=cells(line),r:Record<string,string>={};headers.forEach((h,i)=>r[h]=vals[i]??"");return r;}); }
export function parseCoachManagerCsv(text:string):ParsedDuty[]{return parseCsvRows(text).map((r:Record<string,string>,i:number)=>{const seats=Number(csvValue(r,["seats","capacity","passengers","pax"])||0);return {driver_name:csvValue(r,["driver","drivername","driverid","drivernameid"]),vehicle_id:csvValue(r,["vehicle","vehicleid","registration","reg","fleetnumber"]),vehicle_type:csvValue(r,["vehicletype"]),seats,start_time:time(csvValue(r,["start","starttime"])),pickup_time:time(csvValue(r,["pickup","pickuptime"])),leave_time:time(csvValue(r,["leave","leavetime","departure"])),arrival_time:time(csvValue(r,["arrival","arrivaltime"])),finish_time:time(csvValue(r,["finish","finishtime","end","endtime"])),origin:csvValue(r,["origin","pickupaddress","from","startlocation"]),destination:csvValue(r,["destination","dropoff","dropoffaddress","to","endlocation"]),stay:(csvValue(r,["stay"])||"").toLowerCase()==="yes",back:(csvValue(r,["back"])||"").toLowerCase()==="yes",raw_text:Object.values(r).join(" | "),sort_order:i+1};}).filter((d:ParsedDuty)=>Boolean(d.driver_name||d.vehicle_id||d.origin||d.destination||d.leave_time));}
