import Busboy from "busboy"; import pdfParse from "pdf-parse"; import * as XLSX from "xlsx"; import {createClient} from "@supabase/supabase-js"; import {nanoid} from "nanoid"; import {parseCoachManagerText,parseCoachManagerCsv,parseCoachManagerRows,parsePrivateHireCsv,isPrivateHireCsv} from "../src/lib/coachManagerParser.js";
export const config={api:{bodyParser:false}};
async function readUpload(req:any):Promise<{name:string;buffer:Buffer}>{return new Promise((resolve,reject)=>{const bb=Busboy({headers:req.headers});let name="upload";const chunks:Buffer[]=[];bb.on("file",(_field:any,file:any,info:any)=>{name=info.filename||name;file.on("data",(x:Buffer)=>chunks.push(x));});bb.on("finish",()=>resolve({name,buffer:Buffer.concat(chunks)}));bb.on("error",reject);req.pipe(bb)})}
export default async function handler(req:any,res:any){try{
  if(req.method!=="POST")return res.status(405).json({error:"POST required"});
  const url=process.env.SUPABASE_URL,pub=process.env.SUPABASE_PUBLISHABLE_KEY,internal=process.env.DUTY_CHECKER_DB_KEY;
  if(!url||!pub||!internal)return res.status(503).json({error:"Supabase is not configured in Vercel"});
  const upload=await readUpload(req);if(!upload.buffer.length)return res.status(400).json({error:"CSV or PDF file is required"});
  const isPdf=upload.buffer.subarray(0,5).toString("ascii")==="%PDF-";const isXlsx=upload.buffer.subarray(0,4).toString("binary")==="PK\\x03\\x04";const isCsv=!isPdf&&!isXlsx;
  let duties,rawText="",pageCount=0,sourceType="coach-manager";
  if(isXlsx){const workbook=XLSX.read(upload.buffer,{type:"buffer",cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});duties=parseCoachManagerRows(rows);rawText=JSON.stringify(rows)}
  else if(isCsv){rawText=upload.buffer.toString("utf8");const privateHire=isPrivateHireCsv(rawText);sourceType=privateHire?"private-hire-driver-work-detail":"coach-manager";duties=privateHire?parsePrivateHireCsv(rawText):parseCoachManagerCsv(rawText)}
  else{const parsed=await pdfParse(upload.buffer);rawText=parsed.text;pageCount=parsed.numpages;duties=parseCoachManagerText(rawText)}
  if(!duties.length)return res.status(400).json({error:"No duty rows could be extracted"});
  const db=createClient(url,pub,{global:{headers:{"x-duty-checker-key":internal}}}),importId=nanoid();
  let q=await db.from("duty_imports").insert({id:importId,filename:upload.name,source_url:isXlsx?"uploaded-xlsx":isCsv?"uploaded-csv":"uploaded-pdf",source_type:sourceType,page_count:pageCount,raw_text:rawText,record_count:duties.length});if(q.error)throw q.error;
  const {data:vehicles}=await db.from("vehicles").select("registration,capacity").eq("active",true);const vm=new Map((vehicles??[]).map(v=>[String(v.registration).toUpperCase(),v.capacity]));
  const rows=duties.map(d=>{const cap=d.vehicle_id?vm.get(d.vehicle_id.toUpperCase())??null:null;const issues:string[]=[];if(!d.driver_name)issues.push("Driver name could not be resolved");if(!d.vehicle_id)issues.push("Vehicle ID could not be resolved");if(cap===null)issues.push("Vehicle is not present in capacity master");return {...d,id:nanoid(),import_id:importId,vehicle_capacity:cap,capacity_status:cap===null?"WARN":d.seats>cap?"FAIL":"PASS",data_quality_status:issues.length?"WARN":"PASS",overall_status:"WARN",issues,hours_status:"WARN",hours_issues:["Compliance calculation pending"],wtd_status:"WARN",wtd_issues:["WTD calculation pending"],break_minutes:0,return_leave_time:d.return_leave_time??null,return_arrival_time:d.return_arrival_time??null,return_to_depot:d.return_to_depot,route_stops:d.route_stops??[],arrival_estimated:false,finish_estimated:false,route_status:"NOT_RUN"}});
  q=await db.from("duties").insert(rows);if(q.error)throw q.error;
  const quality={missingDriver:rows.filter(x=>!x.driver_name).length,missingVehicle:rows.filter(x=>!x.vehicle_id).length,missingPickup:rows.filter(x=>!x.pickup_time).length,missingLeave:rows.filter(x=>!x.leave_time).length,missingArrival:rows.filter(x=>!x.arrival_time).length,missingFinish:rows.filter(x=>!x.finish_time).length,missingOrigin:rows.filter(x=>!x.origin).length,missingDestination:rows.filter(x=>!x.destination).length,unresolvedLocationLabels:rows.filter(x=>[x.origin,x.destination].some(v=>v&&/shuttle|route\\s*[0-9]|cleaning|standby|vehicle|coach\\s*[0-9]|ohgs|st bedes|on hire/i.test(v))).length};
  return res.status(200).json({importId,filename:upload.name,pageCount,recordCount:rows.length,sourceType,missingDriver:quality.missingDriver,quality})
}catch(e){return res.status(400).json({error:e instanceof Error?e.message:"Import failed"})}}
