import Busboy from "busboy";
export const config={api:{bodyParser:false}};
async function readUpload(req:any):Promise<{name:string;buffer:Buffer}>{return await new Promise((resolve,reject)=>{const bb=Busboy({headers:req.headers});let name="upload.pdf";const chunks:Buffer[]=[];bb.on("file",(_field:any,file:any,info:any)=>{name=info.filename||name;file.on("data",(x:Buffer)=>chunks.push(x));});bb.on("finish",()=>resolve({name,buffer:Buffer.concat(chunks)}));bb.on("error",reject);req.pipe(bb)})}
import pdfParse from "pdf-parse"; import {createClient} from "@supabase/supabase-js"; import {nanoid} from "nanoid";
const clean=(v:any)=>{const x=String(v??"").replace(/\\s+/g," ").trim();return x||null}; const time=(v:any)=>{const x=clean(v);const m=x?.match(/(\\d{2}:\\d{2})/);return m?.[1]??null};
const nonDrivers=new Set(["ON HIRE","Bus St","Bus School","Shuttle Bus School","Grammar School","Hotel MUFC","Station timetable","RUN RUN"]);
const vehicleTypes=["38EXEC VIP","CAR SDSC","VIPCoach","PSVAR+1","DDSC","DDSB","SDSB","SDSC","Executive","CAR","EXEC"];
const row=/^(?:(?<driver>[A-Za-zÀ-ÿ'’.-]*(?:\\s+[A-Za-zÀ-ÿ'’.-]+){1,4})\\s+)?(?<start>(?:\\d{2}:\\d{2}|\\?\\?:\\?\\?))\\s+(?<pickup>(?:\\d{2}:\\d{2}|\\?\\?:\\?\\?))\\s+(?<origin>.*?)\\s+(?<backFlag>Yes|No)\\s+(?<stay>Yes|No)\\s+(?<destination>.*?)\\s+(?<times>(?:(?:\\d{2}:\\d{2}|\\?\\?:\\?\\?)\\s*){3,4})(?<seats>\\d{1,3})\\s+(?<tail>.+)$/;
function parse(text:string){const lines=text.replace(/\\r/g,"").split(/\\n+/).map(clean).filter(Boolean) as string[];const out:any[]=[];let driver:string|null=null;for(const line of lines){if(/^(Coach Manager Printed:|Bookings - Driver Order|Driver Name Start|Record Count =|ORDER BY DriverID|Driver Name Driver Type)/.test(line))continue;const m=row.exec(line);if(!m?.groups){if(/^[A-Za-zÀ-ÿ'’.-]+(?:\\s+[A-Za-zÀ-ÿ'’.-]+){1,4}$/.test(line)&&!nonDrivers.has(line)&&!line.includes("Printed"))driver=line;continue}const g=m.groups;const ts=(clean(g.times)??"").split(/\\s+/);const type=vehicleTypes.find(t=>(clean(g.tail)??"").startsWith(t))??null;const tail=type?clean(g.tail)!.slice(type.length).trim():clean(g.tail)!;const id=tail.split(/\\s+/)[0]?.replace(/(TM|AP|CH)$/i,"").toUpperCase()??null;const candidate=clean(g.driver);if(candidate&&!nonDrivers.has(candidate))driver=candidate;out.push({driver_name:driver,vehicle_id:id,vehicle_type:type,seats:Number(g.seats),start_time:time(g.start),pickup_time:time(g.pickup),leave_time:time(ts[1]),arrival_time:time(ts[0]),finish_time:time(ts.length===4?ts[3]:ts[2]),origin:clean(g.origin),destination:clean(g.destination),stay:g.stay==="Yes",back:g.backFlag==="Yes",raw_text:line,sort_order:out.length+1});}return out}
export default async function handler(req:any,res:any){try{if(req.method!=="POST")return res.status(405).json({error:"POST required"});const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return res.status(503).json({error:"Supabase is not configured in Vercel yet."});const form=await req.formData();const file=form.get("file");if(!file||typeof file.arrayBuffer!=="function")return res.status(400).json({error:"PDF file is required"});const buffer=Buffer.from(await file.arrayBuffer());const parsed=await pdfParse(buffer);const duties=parse(parsed.text);if(!duties.length)return res.status(400).json({error:"No Coach Manager duty rows could be extracted"});const db=createClient(url,process.env.SUPABASE_PUBLISHABLE_KEY!,{global:{headers:{"x-duty-checker-key":process.env.DUTY_CHECKER_DB_KEY!}}});const importId=nanoid();const {error:ie}=await db.from("duty_imports").insert({id:importId,filename:file.name,source_url:"uploaded-pdf",page_count:parsed.numpages,raw_text:parsed.text,record_count:duties.length});if(ie)throw ie;const {data:vehicles}=await db.from("vehicles").select("registration,capacity").eq("active",true);const vm=new Map((vehicles??[]).map(v=>[v.registration.toUpperCase(),v.capacity]));const rows=duties.map(d=>{const cap=d.vehicle_id?vm.get(d.vehicle_id)??null:null;const issues:string[]=[];if(!d.driver_name)issues.push("Driver name could not be resolved");if(!d.vehicle_id)issues.push("Vehicle ID could not be resolved");if(cap===null)issues.push("Vehicle is not present in capacity master");return {...d,id:nanoid(),import_id:importId,vehicle_capacity:cap,capacity_status:cap===null?"WARN":d.seats>cap?"FAIL":"PASS",data_quality_status:issues.length?"WARN":"PASS",overall_status:"WARN",issues,hours_status:"WARN",hours_issues:["Compliance calculation pending"],wtd_status:"WARN",wtd_issues:["WTD calculation pending"],break_minutes:0,arrival_estimated:false,finish_estimated:false,route_status:"NOT_RUN"} });const {error:de}=await db.from("duties").insert(rows);if(de)throw de;return res.status(200).json({importId,filename:file.name,pageCount:parsed.numpages,recordCount:rows.length});}catch(e){return res.status(400).json({error:e instanceof Error?e.message:"Import failed"})}}